### ISSUE TITLE
cannot run the test project with scala 2.10 RC1

### ISSUE THREAD

**Issue by weejulius** [skipoleschris/xsbt-cucumber-plugin#7] opened 2012-10-24 09:53 UTC
Hi,

I am using scala 2.10 RC1 , it seems the test project cannot run along with it.

The detail of exception is 

Caused by: java.lang.ClassNotFoundException: scala.runtime.AbstractFunction1$mcZL$sp
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[error]         at java.security.AccessController.doPrivileged(Native Method

Thanks

Julius

**Comment by skipoleschris** [comment] 2012-10-24 19:33
Hi,
Thanks for reporting this. I've had a look and I can reproduce it in my build. It looks like the current version of cucumber-jvm for Scala (1.0.14) doesn't work with the 2.10.0-RC1 Scala release. Afraid I can't do much about it until the Cucumber team produce a version compatible with 2.10.0-RC1.

I'll try a personal build of cucumber-jvm against 2.10.0-RC1 and if that solves it then I'll raise an issue with the cucumber team to push out a new build. Watch this space.

**Comment by skipoleschris** [comment] 2012-10-24 20:10
Ok, that's definitely the problem. I downloaded the 1.0.14 release bundle (https://github.com/cucumber/cucumber-jvm/zipball/v1.0.14) and modified the pom.xml to set the scala library and compiler versions to 2.10.0-RC1. I then did a mvn package and generated a new cucumber-scala jar. I then put this into my .ivy2 cache and cucumber now runs fine  in sbt with 2.10.0-RC1.

I'll raise an issue with the cucumber-jvm team to get their release updated. I'll keep this issue open until this is sorted so that you get notified as soon as it is closed.

Hope that helps.
Chris

**Comment by skipoleschris** [comment] 2012-10-25 05:34
Okay, my pull request made it into cucumber-jvm 1.1.0, which came out last night while I was sleeping. I'll upgrade the plugin to use this and push a release out this morning.

**Comment by skipoleschris** [comment] 2012-10-25 06:08
Ok, so as you already saw, the 1.1.0 release of cucumber-jvm didn't make it into the maven repos. As soon as they get the 1.1.1 version done I'll upgrade to support that.

**Comment by skipoleschris** [comment] 2012-10-26 22:24
This is now fixed in the 0.6.2 release that runs using cucumber-jvm 1.1.1 against the Scala 2.10.0-RC1 release.

**Closed as completed by skipoleschris** 2012-10-26 22:24 UTC
